export type ThemeName = 'win95' | 'lofi' | 'fruit-aero' | 'nostalgia-2000' | 'modern';

export interface Theme {
  name: ThemeName;
  label: string;
  vars: Record<string, string>;
}

export const themes: Record<ThemeName, Theme> = {
  'win95': {
    name: 'win95',
    label: 'Windows 95',
    vars: {
      '--bg': '#C0C0C0',
      '--title-active': '#000080',
      '--title-inactive': '#808080',
      '--highlight': '#FFFFFF',
      '--shadow': '#808080',
      '--dark-shadow': '#404040',
      '--text': '#000000',
      '--input-bg': '#FFFFFF',
      '--button-face': '#C0C0C0',
      '--border-style': 'outset',
      '--border-width': '2px',
      '--border-radius': '0px',
      '--font-family': "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
      '--font-size': '11px',
      '--titlebar-gradient': 'linear-gradient(90deg, #000080, #1084d0)',
      '--titlebar-color': 'white',
      '--scrollbar-track': '#C0C0C0',
      '--scrollbar-thumb': '#C0C0C0',
      '--user-msg-bg': '#000080',
      '--user-msg-text': 'white',
      '--assistant-msg-bg': '#FFFFCC',
      '--assistant-msg-text': '#000000',
      '--system-msg-bg': '#E0E0E0',
      '--system-msg-text': '#404040',
      '--prose-code-bg': '#E0E0E0',
      '--prose-pre-bg': '#FFFFFF',
      '--prose-blockquote-border': '#808080',
      '--prose-blockquote-text': '#404040',
      '--link-color': '#000080',
    },
  },

  'lofi': {
    name: 'lofi',
    label: 'Lo-fi',
    vars: {
      '--bg': '#F5E6D3',
      '--title-active': '#8B6F47',
      '--title-inactive': '#A68B6B',
      '--highlight': '#FFF8F0',
      '--shadow': '#C4A882',
      '--dark-shadow': '#7A5C38',
      '--text': '#4A3728',
      '--input-bg': '#FFFDF9',
      '--button-face': '#E8D5C0',
      '--border-style': 'outset',
      '--border-width': '2px',
      '--border-radius': '4px',
      '--font-family': "'Georgia', 'Times New Roman', serif",
      '--font-size': '12px',
      '--titlebar-gradient': 'linear-gradient(90deg, #8B6F47, #A68B6B)',
      '--titlebar-color': '#FFF8F0',
      '--scrollbar-track': '#E8D5C0',
      '--scrollbar-thumb': '#D4C0A8',
      '--user-msg-bg': '#8B6F47',
      '--user-msg-text': '#FFF8F0',
      '--assistant-msg-bg': '#FFFDF9',
      '--assistant-msg-text': '#4A3728',
      '--system-msg-bg': '#E8D5C0',
      '--system-msg-text': '#7A5C38',
      '--prose-code-bg': '#E8D5C0',
      '--prose-pre-bg': '#FFFDF9',
      '--prose-blockquote-border': '#C4A882',
      '--prose-blockquote-text': '#7A5C38',
      '--link-color': '#8B6F47',
    },
  },

  'fruit-aero': {
    name: 'fruit-aero',
    label: 'Fruit Aero',
    vars: {
      '--bg': '#E8F4F8',
      '--title-active': '#FF6B6B',
      '--title-inactive': '#FFB347',
      '--highlight': '#FFFFFF',
      '--shadow': '#B8D4E3',
      '--dark-shadow': '#5B9BD5',
      '--text': '#2C3E50',
      '--input-bg': '#FFFFFF',
      '--button-face': '#E0F0FF',
      '--border-style': 'outset',
      '--border-width': '2px',
      '--border-radius': '8px',
      '--font-family': "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
      '--font-size': '11px',
      '--titlebar-gradient': 'linear-gradient(90deg, #FF6B6B, #FFB347, #4ECDC4)',
      '--titlebar-color': 'white',
      '--scrollbar-track': '#E0F0FF',
      '--scrollbar-thumb': '#B8D4E3',
      '--user-msg-bg': '#FF6B6B',
      '--user-msg-text': 'white',
      '--assistant-msg-bg': '#F0FFF4',
      '--assistant-msg-text': '#2C3E50',
      '--system-msg-bg': '#E0F0FF',
      '--system-msg-text': '#5B9BD5',
      '--prose-code-bg': '#E0F0FF',
      '--prose-pre-bg': '#FFFFFF',
      '--prose-blockquote-border': '#4ECDC4',
      '--prose-blockquote-text': '#5B9BD5',
      '--link-color': '#FF6B6B',
    },
  },

  'nostalgia-2000': {
    name: 'nostalgia-2000',
    label: 'Nostalgia 2000',
    vars: {
      '--bg': '#3A6EA5',
      '--title-active': '#0054E3',
      '--title-inactive': '#7B96B8',
      '--highlight': '#FFFFFF',
      '--shadow': '#5C8FBF',
      '--dark-shadow': '#003580',
      '--text': '#000000',
      '--input-bg': '#FFFFFF',
      '--button-face': '#ECE9D8',
      '--border-style': 'outset',
      '--border-width': '2px',
      '--border-radius': '3px',
      '--font-family': "'Tahoma', 'Segoe UI', sans-serif",
      '--font-size': '11px',
      '--titlebar-gradient': 'linear-gradient(180deg, #0058EE 3%, #3C8FFF 6%, #1F6FE0 9%, #0054E3 12%, #0049D6 25%, #0043CC 50%, #0041C8 75%, #003DB5 100%)',
      '--titlebar-color': 'white',
      '--scrollbar-track': '#ECE9D8',
      '--scrollbar-thumb': '#C8C0B0',
      '--user-msg-bg': '#0054E3',
      '--user-msg-text': 'white',
      '--assistant-msg-bg': '#FFFFCC',
      '--assistant-msg-text': '#000000',
      '--system-msg-bg': '#ECE9D8',
      '--system-msg-text': '#003580',
      '--prose-code-bg': '#ECE9D8',
      '--prose-pre-bg': '#FFFFFF',
      '--prose-blockquote-border': '#5C8FBF',
      '--prose-blockquote-text': '#003580',
      '--link-color': '#0054E3',
    },
  },

  'modern': {
    name: 'modern',
    label: 'Moderno',
    vars: {
      '--bg': '#0F0F0F',
      '--title-active': '#1A1A2E',
      '--title-inactive': '#2D2D44',
      '--highlight': '#2A2A3E',
      '--shadow': '#1A1A2E',
      '--dark-shadow': '#0A0A14',
      '--text': '#E0E0E0',
      '--input-bg': '#1A1A2E',
      '--button-face': '#2A2A3E',
      '--border-style': 'solid',
      '--border-width': '1px',
      '--border-radius': '12px',
      '--font-family': "'Inter', 'Segoe UI', system-ui, sans-serif",
      '--font-size': '13px',
      '--titlebar-gradient': 'linear-gradient(90deg, #667EEA, #764BA2)',
      '--titlebar-color': 'white',
      '--scrollbar-track': '#1A1A2E',
      '--scrollbar-thumb': '#3D3D56',
      '--user-msg-bg': 'linear-gradient(135deg, #667EEA, #764BA2)',
      '--user-msg-text': 'white',
      '--assistant-msg-bg': '#1A1A2E',
      '--assistant-msg-text': '#E0E0E0',
      '--system-msg-bg': '#2D2D44',
      '--system-msg-text': '#A0A0B0',
      '--prose-code-bg': '#2D2D44',
      '--prose-pre-bg': '#1A1A2E',
      '--prose-blockquote-border': '#667EEA',
      '--prose-blockquote-text': '#A0A0B0',
      '--link-color': '#667EEA',
    },
  },
};

export const themeNames = Object.keys(themes) as ThemeName[];
